-- Monitors.
--
-- Deliberately NOT named monitors.lua: hyde.lua does check_require("monitors")
-- for configs generated by nwg-displays, which would overwrite a hand-written
-- file there.
--
-- Monitor descriptions live in utils.lua.
--
-- Everything here is a plain declarative rule -- no docked/undocked branching.
-- Hyprland stores monitor rules and re-applies them itself each time a monitor
-- appears, so one static rule per output covers both states. (Top-level Lua is
-- the opposite: it runs once at parse and never again, which is why the
-- workspace rules next door need utils.on_ultrawide_change.)

-- pcall'd so a broken utils.lua surfaces as one readable message instead of a
-- bare traceback out of the middle of the config parse.
local ok, utils = pcall(require, "utils")
if not ok then
	error("utils.lua failed to load: " .. tostring(utils), 0)
end

-- Framework 16 internal panel -- the origin, docked or not.
hl.monitor({
	output = utils.laptop,
	mode = "preferred",
	position = "0x0",
	scale = 1.2,
})

-- Samsung 34" ultrawide -- sits to the right of the laptop when docked.
--
-- Positioned explicitly rather than with `auto-right`: the auto-* placements
-- depend on which output Hyprland enumerates first, and if the ultrawide came
-- up before eDP-1 it would take 0x0 and the two would overlap. 2560 is the
-- laptop panel's width at scale 1.
--
-- NOTE: Pinned at 60 Hz. The panel supports 99.98 Hz natively, but our
-- current cable/dock can't sustain that bandwidth (caused display flicker).
-- Try @99.98 again only with a known-good DP 1.2+ cable directly attached.
hl.monitor({
	output = utils.ultrawide,
	mode = "preferred",
	position = "2560x0",
	scale = 1,
})

-- Catch-all for any other hot-plugged display (TV, projector, etc.) -- mirrors
-- the laptop rather than extending the desktop onto an unknown panel.
hl.monitor({
	output = "",
	mode = "preferred",
	position = "0x0",
	scale = 1,
	mirror = utils.laptop,
})
