# User overrides — sourced by ~/.local/share/hypr/hyprland.conf after HyDE core loads

$XDG_CONFIG_HOME = $HOME/.config

source = $XDG_CONFIG_HOME/hypr/keybindings.conf
source = $XDG_CONFIG_HOME/hypr/userprefs.conf
source = $XDG_CONFIG_HOME/hypr/monitors.conf
source = $XDG_CONFIG_HOME/hypr/ultrawide.conf
